Repository milieuinfo/webcomponent-vl-ui-multiselect, pull requests merged in 2019-09, with the labels that each got.

#23 UIG-218
  vl-multiselect.src.js
Labels: maintenance

#24 Update link naar demo
  vl-multiselect.src.js
Labels: maintenance

#25 Automatic commit via update script
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/task.md
  package-lock.json
  package.json
Labels: maintenance

#11 Update dependency sinon to v7.4.1
  package-lock.json
  package.json
Labels: renovate

#10 Update dependency replace to v1.1.0
  package-lock.json
  package.json
Labels: renovate

#9 Update dependency np to v3.1.0
  package-lock.json
  package.json
Labels: renovate

#26 Fix corrupt package-lock
  package-lock.json
Labels: bug

#32 Update dependency vl-ui-core to v1.4.6
  package-lock.json
  package.json
Labels: dependencies

#31 Update dependency sinon to v7.4.2
  package-lock.json
  package.json
Labels: dependencies

#30 Update dependency replace to v1.1.1
  package-lock.json
  package.json
Labels: dependencies

#29 Update dependency @govflanders/vl-ui-util to v3.9.0
  package-lock.json
  package.json
Labels: dependencies

#28 Update dependency @govflanders/vl-ui-pill to v3.9.0
  package-lock.json
  package.json
Labels: dependencies

#27 Update dependency @govflanders/vl-ui-core to v3.9.0
  package-lock.json
  package.json
Labels: dependencies

#33 Revert naar @govflanders 3.7.2
  package-lock.json
  package.json
Labels: bug

#34 Update package-lock
  package-lock.json
  package.json
Labels: bug

#35 Update package-lock
  demo/demo.css
  package-lock.json
  package.json
  style.css
Labels: bug

#38 Automatic commit via update script
  demo/demo.css
  package-lock.json
  style.css
Labels: maintenance

#40 Update and install latest util
  .github/ISSUE_TEMPLATE/task.md
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
  style.css
Labels: maintenance
