Repository milieuinfo/webcomponent-vl-ui-multiselect, pull requests merged in 2020-08, with the labels that each got.

#107 Update dependency @govflanders/vl-ui-form-structure to v3.11.5
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#108 Update dependency @govflanders/vl-ui-input-field to v3.11.5
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#109 Update dependency @govflanders/vl-ui-select to v3.11.5
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#110 Update dependency @govflanders/vl-ui-multiselect to v3.11.5
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#113 Upgrade huisstijl versie 3.11.5
  demo/vl-multiselect.html
  index.js
  package-lock.json
  package.json
  src/style.css
  src/style.scss
  src/vl-multiselect.js
  test/e2e/components/pill.js
  test/e2e/components/vl-multiselect.js
  test/e2e/multiselect.test.js
  test/e2e/pages/vl-multiselect.page.js
Labels: chore

#106 Als de geselecteerde tekst lang is, wordt dit goed weergegeven bij de multiselect
  dist/style.css
  dist/style.scss
  src/style.css
  src/style.scss
Labels: bug

#115 Update dependencies
  dist/style.css
  package-lock.json
  package.json
  src/style.css
Labels: chore
