Repository milieuinfo/webcomponent-vl-ui-multiselect, pull requests merged in 2021-06, with the labels that each got.

#147 Update dependencies
  package-lock.json
  package.json
  src/style.css
  src/style.css.map
Labels: chore

#145 Update dependency vl-ui-form-validation to ^4.0.0
  package.json
Labels: chore, dependencies, renovate

#148 Aanwezigheid `multiple` attribuut is niet meer nodig om aan te geven dat de component een multiselect is
  demo/vl-multiselect.html
  src/vl-multiselect.js
  test/unit/vl-multiselect.test.html
Labels: enhancement

#149 Update vl-ui-util.
  .prettierrc.json
  package-lock.json
  package.json
  src/vl-multiselect.js
Labels: chore
